import datetime
import json
import os
import re
import shutil
import time
from neon_ai.database.connection import get_connection
from psycopg2.extras import RealDictCursor

# Automation is now fully ungated; keep a very early cutoff so the existing
# sweeper queries still work without excluding historical purchase orders.
AUTOMATION_MIN_DATE = datetime.date(1900, 1, 1)
PO_DISPATCH_LOG_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "po_dispatch_log.json")
LEGACY_PO_AUTO_SEND_ENV = "NEON_ENABLE_LEGACY_PO_AUTO_SEND"
BACKGROUND_VENDOR_PO_FOLLOWUPS_ENV = "NEON_ENABLE_BACKGROUND_VENDOR_PO_FOLLOWUPS"


def _perf_log(area: str, name: str, started_at: float) -> None:
    elapsed_ms = (time.perf_counter() - started_at) * 1000.0
    print(f"[PERF] area={area} name={name} elapsed_ms={elapsed_ms:.2f}")


def _background_vendor_po_followups_enabled() -> bool:
    return str(os.getenv(BACKGROUND_VENDOR_PO_FOLLOWUPS_ENV, "0")).strip().lower() in {"1", "true", "yes", "on"}


def ensure_purchase_schema():
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('ALTER TABLE public."PurchaseOrder" ADD COLUMN IF NOT EXISTS "ExpectedArrivalDate" date')
        cur.execute('ALTER TABLE public."PurchaseOrder" ADD COLUMN IF NOT EXISTS "ExpectedArrivalNote" text')
        cur.execute('ALTER TABLE public."PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "QuantityReceived" numeric DEFAULT 0')
        cur.execute('ALTER TABLE public."PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "LastReceivedDate" date')
        cur.execute('ALTER TABLE public."PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "LastPackingSlip" text')
        cur.execute('ALTER TABLE public."PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "CatalogItemID" integer')
        cur.execute('CREATE SEQUENCE IF NOT EXISTS "PurchaseOrderItemSourceLink_POItemSourceLinkID_seq"')
        cur.execute(
            '''
            CREATE TABLE IF NOT EXISTS public."PurchaseOrderItemSourceLink" (
                "POItemSourceLinkID" integer NOT NULL DEFAULT nextval('"PurchaseOrderItemSourceLink_POItemSourceLinkID_seq"'::regclass),
                "POItemID" integer NOT NULL,
                "PurchaseOrderID" integer NOT NULL,
                "RFQCarriedSelectionID" integer,
                "PriceRequestID" integer,
                "PRItemID" integer,
                "VendorID" integer,
                "EstimateID" integer,
                "MaterialID" integer,
                "CreatedAt" timestamptz DEFAULT NOW(),
                CONSTRAINT "PurchaseOrderItemSourceLink_pkey" PRIMARY KEY ("POItemSourceLinkID")
            )
            '''
        )
        cur.execute(
            '''
            CREATE UNIQUE INDEX IF NOT EXISTS "idx_poitemsourcelink_poi"
            ON public."PurchaseOrderItemSourceLink" ("POItemID")
            '''
        )
        cur.execute(
            '''
            CREATE TABLE IF NOT EXISTS public."PurchaseOrderReceipt" (
                "ReceiptID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PurchaseOrderID" integer NOT NULL,
                "DocumentType" text,
                "DocumentRef" text NOT NULL,
                "ReceiveDate" date,
                "CreatedAt" timestamptz DEFAULT NOW()
            )
            '''
        )
        cur.execute(
            '''
            CREATE TABLE IF NOT EXISTS public."PurchaseOrderReceiptItem" (
                "ReceiptItemID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ReceiptID" integer NOT NULL,
                "POItemID" integer NOT NULL,
                "QuantityReceived" numeric DEFAULT 0
            )
            '''
        )
        conn.commit()
    finally:
        conn.close()


def load_po_dispatch_log():
    if not os.path.exists(PO_DISPATCH_LOG_PATH):
        return []
    try:
        with open(PO_DISPATCH_LOG_PATH, "r", encoding="utf-8") as handle:
            data = json.load(handle)
        return data if isinstance(data, list) else []
    except Exception:
        return []


def save_po_dispatch_log(entries):
    with open(PO_DISPATCH_LOG_PATH, "w", encoding="utf-8") as handle:
        json.dump(entries, handle, indent=2)


def upsert_po_dispatch_record(po_id: int, updates: dict):
    entries = load_po_dispatch_log()
    for entry in entries:
        if entry.get("po_id") == po_id:
            entry.update(updates)
            save_po_dispatch_log(entries)
            return entry

    new_entry = {"po_id": po_id}
    new_entry.update(updates)
    entries.append(new_entry)
    save_po_dispatch_log(entries)
    return new_entry

# ==========================================
# 1. VENDOR & INVOICE LOGIC (Legacy Support)
# ==========================================

def insert_vendor(account_number, vendor_name, vendor_address, vendor_city, contact_name, contact_number):
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('''
            INSERT INTO "Vendor" ("AccountNumber", "VendorName", "VendorAddressNumber", "VendorCity", "VendorContactName", "VendorContactNumber")
            VALUES (%s, %s, %s, %s, %s, %s)
        ''', (account_number, vendor_name, vendor_address, vendor_city, contact_name, contact_number))
        conn.commit()
    finally:
        conn.close()

def get_vendors():
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('SELECT * FROM "Vendor" ORDER BY "VendorName"')
        return cur.fetchall()
    finally:
        conn.close()

def insert_vendor_invoice(invoice_number, po_id, inv_date, due_date, amount, status, description):
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('''
            INSERT INTO "VendorInvoice" ("VendorInvoiceNumber", "PurchaseOrderID", "VendorInvoiceDate", "VendorInvoiceDueDate", "VendorInvoiceAmount", "VendorInvoiceStatus", "Description")
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        ''', (invoice_number, po_id, inv_date, due_date, amount, status, description))
        conn.commit()
    finally:
        conn.close()

# ==========================================
# 2. PO COMMAND CENTER ENGINE (New Workflow)
# ==========================================

def get_carried_items_for_po_builder(rfq_id: int):
    """
    Calculates backlog for the PO Builder UI.
    """
    from neon_ai.database.connection import get_connection
    from psycopg2.extras import RealDictCursor
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT 
                em."EstimateMaterialID" AS "mat_id", 
                em."Description", 
                em."Quantity" AS "QuotedQty",
                pri."QuotedUnitPrice" AS "price",
                COALESCE((
                    SELECT SUM(poi."QuantityOrdered") 
                    FROM "PurchaseOrderItem" poi 
                    -- THE FIX: We use poi."MaterialID" here!
                    WHERE poi."MaterialID" = em."EstimateMaterialID"
                ), 0) AS "PreviouslyOrdered"
            FROM "EstimateMaterial" em
            JOIN "PriceRequestItem" pri ON em."EstimateMaterialID" = pri."MaterialID"
            WHERE pri."PriceRequestID" = %s AND pri."IsCarried" = TRUE
            ORDER BY em."Description"
        ''', (rfq_id,))
        return cur.fetchall()
    finally:
        conn.close()


def get_carried_items_for_po_center(
    work_order_id: int,
    estimate_id: int | None = None,
    rfq_id: int | None = None,
    vendor_id: int | None = None,
):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute(
            '''
            SELECT
                wo."WorkOrderID",
                wo."SourceEstimateID"
            FROM "WorkOrder" wo
            WHERE wo."WorkOrderID" = %s
            ''',
            (work_order_id,),
        )
        work_order = cur.fetchone()
        if not work_order:
            return []

        source_estimate_id = estimate_id or work_order.get("SourceEstimateID")
        filter_params = [work_order_id]
        rfq_filters = []
        if source_estimate_id:
            rfq_filters.append('rcs."EstimateID" = %s')
            filter_params.append(source_estimate_id)
        if rfq_id:
            rfq_filters.append('rcs."SourcePriceRequestID" = %s')
            filter_params.append(rfq_id)
        if vendor_id:
            rfq_filters.append('rcs."VendorID" = %s')
            filter_params.append(vendor_id)
        rfq_where = (" AND " + " AND ".join(rfq_filters)) if rfq_filters else ""

        cur.execute(
            f'''
            SELECT
                rcs."RFQCarriedSelectionID",
                rcs."EstimateID",
                rcs."SourcePriceRequestID" AS "PriceRequestID",
                rcs."SourcePRItemID" AS "PRItemID",
                rcs."VendorID",
                rcs."MaterialID",
                rcs."CarriedQuantity",
                rcs."CarriedUnitPrice",
                rcs."CarriedExtendedPrice",
                em."ItemID" AS "CatalogItemID",
                COALESCE(NULLIF(TRIM(v."VendorName"), ''), 'Unknown Vendor') AS "VendorName",
                COALESCE(NULLIF(TRIM(em."PartNumber"), ''), NULLIF(TRIM(m."PartNumber"), ''), '') AS "PartNumber",
                COALESCE(NULLIF(TRIM(em."Description"), ''), NULLIF(TRIM(m."Description"), ''), '') AS "Description",
                COALESCE(NULLIF(TRIM(m."Unit"), ''), '') AS "Unit",
                pr."PriceRequestID" AS "RFQID",
                pr."EstimateID" AS "RFQEstimateID",
                wo."WorkOrderID",
                COALESCE(NULLIF(TRIM(pr."Status"), ''), 'Draft') AS "RFQStatus",
                COALESCE(NULLIF(TRIM(rcs."SelectionType"), ''), 'LineItem') AS "SelectionType"
            FROM "RFQCarriedSelection" rcs
            JOIN "PriceRequest" pr ON rcs."SourcePriceRequestID" = pr."PriceRequestID"
            JOIN "EstimateMaterial" em ON rcs."MaterialID" = em."EstimateMaterialID"
            LEFT JOIN "Material" m ON em."ItemID" = m."ItemID"
            LEFT JOIN "Vendor" v ON rcs."VendorID" = v."VendorID"
            JOIN "WorkOrder" wo ON wo."WorkOrderID" = %s
            WHERE (
                wo."SourceEstimateID" = rcs."EstimateID"
                OR em."EstimateID" = wo."SourceEstimateID"
            )
            {rfq_where}
            ORDER BY v."VendorName" ASC, pr."PriceRequestID" ASC, em."Description" ASC
            ''',
            tuple(filter_params),
        )
        rows = [dict(row) for row in cur.fetchall()]
        seen_selection_ids = {int(row["RFQCarriedSelectionID"]) for row in rows if row.get("RFQCarriedSelectionID") is not None}

        legacy_filters = ['wo."WorkOrderID" = %s']
        legacy_params = [work_order_id]
        if source_estimate_id:
            legacy_filters.append('pr."EstimateID" = %s')
            legacy_params.append(source_estimate_id)
        if rfq_id:
            legacy_filters.append('pr."PriceRequestID" = %s')
            legacy_params.append(rfq_id)
        if vendor_id:
            legacy_filters.append('pr."VendorID" = %s')
            legacy_params.append(vendor_id)

        cur.execute(
            f'''
            SELECT
                NULL::integer AS "RFQCarriedSelectionID",
                pr."EstimateID",
                pr."PriceRequestID",
                pri."PRItemID",
                pr."VendorID",
                pri."MaterialID",
                COALESCE(pri."QuantityOverride", em."Quantity", 0) AS "CarriedQuantity",
                COALESCE(pri."QuotedUnitPrice", 0) AS "CarriedUnitPrice",
                COALESCE(pri."QuotedUnitPrice", 0) * COALESCE(pri."QuantityOverride", em."Quantity", 0) AS "CarriedExtendedPrice",
                em."ItemID" AS "CatalogItemID",
                COALESCE(NULLIF(TRIM(v."VendorName"), ''), 'Unknown Vendor') AS "VendorName",
                COALESCE(NULLIF(TRIM(em."PartNumber"), ''), NULLIF(TRIM(m."PartNumber"), ''), '') AS "PartNumber",
                COALESCE(NULLIF(TRIM(em."Description"), ''), NULLIF(TRIM(m."Description"), ''), '') AS "Description",
                COALESCE(NULLIF(TRIM(m."Unit"), ''), '') AS "Unit",
                pr."PriceRequestID" AS "RFQID",
                pr."EstimateID" AS "RFQEstimateID",
                wo."WorkOrderID",
                COALESCE(NULLIF(TRIM(pr."Status"), ''), 'Draft') AS "RFQStatus",
                'LegacyCarry' AS "SelectionType"
            FROM "PriceRequestItem" pri
            JOIN "PriceRequest" pr ON pri."PriceRequestID" = pr."PriceRequestID"
            JOIN "EstimateMaterial" em ON pri."MaterialID" = em."EstimateMaterialID"
            LEFT JOIN "Material" m ON em."ItemID" = m."ItemID"
            LEFT JOIN "Vendor" v ON pr."VendorID" = v."VendorID"
            JOIN "WorkOrder" wo ON wo."WorkOrderID" = %s
            WHERE pri."IsCarried" = TRUE
              AND ({' AND '.join(legacy_filters)})
            ORDER BY v."VendorName" ASC, pr."PriceRequestID" ASC, em."Description" ASC
            ''',
            tuple([work_order_id] + legacy_params),
        )
        for row in cur.fetchall():
            row_dict = dict(row)
            synthetic_key = f"legacy:{row_dict.get('PRItemID')}"
            if synthetic_key in seen_selection_ids:
                continue
            if any(
                existing.get("PRItemID") == row_dict.get("PRItemID")
                for existing in rows
            ):
                continue
            rows.append(row_dict)

        return rows
    finally:
        conn.close()


def get_purchase_order_source_links(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute(
            '''
            SELECT
                sl."POItemID",
                sl."RFQCarriedSelectionID",
                sl."PriceRequestID",
                sl."PRItemID",
                sl."VendorID",
                sl."EstimateID",
                sl."MaterialID"
            FROM "PurchaseOrderItemSourceLink" sl
            WHERE sl."PurchaseOrderID" = %s
            ''',
            (po_id,),
        )
        return [dict(row) for row in cur.fetchall()]
    finally:
        conn.close()

def _insert_purchase_order_items(cur, po_id: int, items: list, commit_estimate_lines: bool):
    inserted_po_item_ids = []
    for item in items:
        estimate_material_id = item.get('estimate_material_id')
        if estimate_material_id in (None, ""):
            estimate_material_id = item.get('mat_id')
        catalog_item_id = item.get('catalog_item_id')
        if catalog_item_id in (None, ""):
            catalog_item_id = item.get('item_id')
        qty = float(item.get('qty') or 0)
        price = float(item.get('price') or 0)
        desc = item.get('desc') or item.get('description')
        cur.execute('''
            INSERT INTO "PurchaseOrderItem" 
            ("PurchaseOrderID", "MaterialID", "CatalogItemID", "QuantityOrdered", "UnitPriceAtOrder", "LineTotal", "Description")
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING "POItemID"
        ''', (
            po_id,
            estimate_material_id,
            catalog_item_id,
            qty,
            price,
            qty * price,
            desc,
        ))
        inserted_po_item_ids.append(int(cur.fetchone()["POItemID"]))

        if commit_estimate_lines and estimate_material_id:
            cur.execute('''
                UPDATE "EstimateMaterial" 
                SET "IsCommitted" = TRUE,
                    "CommittedUnitCost" = %s,
                    "CommittedLineTotal" = %s,
                    "IsOrdered" = CASE 
                        WHEN ("Quantity" <= (
                            SELECT SUM("QuantityOrdered") 
                            FROM "PurchaseOrderItem" 
                            WHERE "MaterialID" = %s
                        )) THEN TRUE ELSE FALSE END
                WHERE "EstimateMaterialID" = %s
            ''', (price, qty * price, estimate_material_id, estimate_material_id))
    return inserted_po_item_ids


def _save_purchase_order_record(
    work_order_id: int,
    items: list,
    vendor_id: int = None,
    status: str = "Locked",
    expected_date=None,
    expected_note: str = None,
    po_id: int = None,
):
    ensure_purchase_schema()
    validate_work_order_for_purchase_order(work_order_id)
    from neon_ai.database.connection import get_connection
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        total_val = sum(float(item.get('qty') or 0) * float(item.get('price') or 0) for item in items)
        status_text = str(status or "Draft").strip() or "Draft"
        commit_estimate_lines = status_text != "Draft"

        if po_id:
            cur.execute(
                '''
                SELECT "PurchaseOrderID", COALESCE("Status", '') AS "Status"
                FROM "PurchaseOrder"
                WHERE "PurchaseOrderID" = %s
                ''',
                (po_id,),
            )
            existing = cur.fetchone()
            if not existing:
                raise ValueError(f"Purchase Order #{po_id} was not found.")
            existing_status = str(existing.get("Status") or "").strip()
            if existing_status and existing_status not in {"Draft", "Locked"}:
                raise ValueError(f"Purchase Order #{po_id} is already {existing_status} and can no longer be rewritten from this workspace.")

            cur.execute(
                '''
                UPDATE "PurchaseOrder"
                SET "WorkOrderID" = %s,
                    "VendorID" = %s,
                    "Status" = %s,
                    "PurchaseOrderTotal" = %s,
                    "ExpectedArrivalDate" = %s,
                    "ExpectedArrivalNote" = %s,
                    "ShippingDocuments" = NULL
                WHERE "PurchaseOrderID" = %s
                ''',
                (work_order_id, vendor_id, status_text, total_val, expected_date or None, expected_note or None, po_id),
            )
            cur.execute('DELETE FROM "PurchaseOrderItem" WHERE "PurchaseOrderID" = %s', (po_id,))
            target_po_id = int(po_id)
        else:
            cur.execute('''
                INSERT INTO "PurchaseOrder" 
                ("WorkOrderID", "VendorID", "Date", "Status", "PurchaseOrderTotal", "ExpectedArrivalDate", "ExpectedArrivalNote")
                VALUES (%s, %s, CURRENT_DATE, %s, %s, %s, %s)
                RETURNING "PurchaseOrderID"
            ''', (work_order_id, vendor_id, status_text, total_val, expected_date or None, expected_note or None))
            target_po_id = int(cur.fetchone()["PurchaseOrderID"])

        if po_id:
            cur.execute('DELETE FROM "PurchaseOrderItemSourceLink" WHERE "PurchaseOrderID" = %s', (target_po_id,))
        inserted_po_item_ids = _insert_purchase_order_items(cur, target_po_id, items, commit_estimate_lines=commit_estimate_lines)
        for po_item_id, item in zip(inserted_po_item_ids, items):
            source_selection_id = item.get("rfq_carried_selection_id")
            source_price_request_id = item.get("source_price_request_id") or item.get("rfq_id")
            source_pr_item_id = item.get("source_pr_item_id")
            source_vendor_id = item.get("source_vendor_id") or item.get("vendor_id")
            source_estimate_id = item.get("source_estimate_id") or item.get("estimate_id")
            source_material_id = item.get("estimate_material_id") or item.get("mat_id")
            if all(
                value in (None, "", 0, "0")
                for value in (
                    source_selection_id,
                    source_price_request_id,
                    source_pr_item_id,
                    source_vendor_id,
                    source_estimate_id,
                    source_material_id,
                )
            ):
                continue
            cur.execute(
                '''
                INSERT INTO "PurchaseOrderItemSourceLink" (
                    "POItemID",
                    "PurchaseOrderID",
                    "RFQCarriedSelectionID",
                    "PriceRequestID",
                    "PRItemID",
                    "VendorID",
                    "EstimateID",
                    "MaterialID"
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                ''',
                (
                    po_item_id,
                    target_po_id,
                    source_selection_id or None,
                    source_price_request_id or None,
                    source_pr_item_id or None,
                    source_vendor_id or None,
                    source_estimate_id or None,
                    source_material_id or None,
                ),
            )
        conn.commit()
        return target_po_id
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

def save_new_purchase_order(
    work_order_id: int,
    items: list,
    vendor_id: int = None,
    rfq_id: int = None,
    status: str = "Locked",
    expected_date=None,
    expected_note: str = None,
):
    """
    The Master Transaction. 
    1. Creates PO Header.
    2. Batch inserts PO Items (respecting the database structure!).
    3. Updates 'IsCommitted' and 'IsOrdered' on EstimateMaterial.
    """
    return _save_purchase_order_record(
        work_order_id=work_order_id,
        items=items,
        vendor_id=vendor_id,
        status=status,
        expected_date=expected_date,
        expected_note=expected_note,
        po_id=None,
    )


def save_purchase_order_draft(
    work_order_id: int,
    items: list,
    vendor_id: int = None,
    po_id: int = None,
    expected_date=None,
    expected_note: str = None,
):
    return _save_purchase_order_record(
        work_order_id=work_order_id,
        items=items,
        vendor_id=vendor_id,
        status="Draft",
        expected_date=expected_date,
        expected_note=expected_note,
        po_id=po_id,
    )


def lock_purchase_order_record(
    work_order_id: int,
    items: list,
    vendor_id: int = None,
    po_id: int = None,
    expected_date=None,
    expected_note: str = None,
):
    return _save_purchase_order_record(
        work_order_id=work_order_id,
        items=items,
        vendor_id=vendor_id,
        status="Locked",
        expected_date=expected_date,
        expected_note=expected_note,
        po_id=po_id,
    )

def get_po_export_data(po_id: int):
    """
    Pulls data for Word Generator. 
    FIXED: Uses StreetNumber/StreetName instead of old SiteAddress.
    """
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT 
                po."PurchaseOrderID",
                po."PurchaseOrderID" AS "PONumber",
                po."Date",
                po."Status",
                po."ShippingDocuments",
                po."ExpectedArrivalDate",
                po."ExpectedArrivalNote",
                v."VendorName", v."AccountNumber", 
                v."VendorAddressNumber" AS "VendorAddress",
                v."VendorID",
                wo."WorkOrderID", 
                wo."SourceEstimateID" AS "EstimateID",
                s."SiteName", 
                s."StreetNumber", s."StreetName",
                c."CustomerName"
            FROM "PurchaseOrder" po
            JOIN "Vendor" v ON po."VendorID" = v."VendorID"
            LEFT JOIN "WorkOrder" wo ON po."WorkOrderID" = wo."WorkOrderID"
            LEFT JOIN "Site" s ON wo."SiteID" = s."SiteID"
            LEFT JOIN "Customer" c ON s."CustomerID" = c."CustomerID"
            WHERE po."PurchaseOrderID" = %s
        ''', (po_id,))
        return cur.fetchone()
    finally:
        conn.close()

def get_po_items(po_id: int):
    """Pulls the line items for a specific Purchase Order."""
    from neon_ai.database.connection import get_connection
    from psycopg2.extras import RealDictCursor
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT
                poi."QuantityOrdered",
                COALESCE(poi."Description", em."Description", m."Description") AS "Description",
                COALESCE(
                    NULLIF(poi."UnitPriceAtOrder", 0),
                    NULLIF(em."CommittedUnitCost", 0),
                    NULLIF(em."AwardedUnitCost", 0),
                    NULLIF(em."UnitCost", 0),
                    CASE COALESCE(m."CarryPriceSource", 'Internal')
                        WHEN 'Nedco' THEN NULLIF(m."NedcoPrice", 0)
                        WHEN 'Gescan' THEN NULLIF(m."GescanPrice", 0)
                        WHEN 'Eecol' THEN NULLIF(m."EecolPrice", 0)
                        WHEN 'Guillevin' THEN NULLIF(m."GuillevinPrice", 0)
                        ELSE NULLIF(m."InternalPrice", 0)
                    END,
                    0
                ) AS "UnitPriceAtOrder",
                COALESCE(
                    NULLIF(poi."LineTotal", 0),
                    COALESCE(poi."QuantityOrdered", 0) * COALESCE(
                        NULLIF(poi."UnitPriceAtOrder", 0),
                        NULLIF(em."CommittedUnitCost", 0),
                        NULLIF(em."AwardedUnitCost", 0),
                        NULLIF(em."UnitCost", 0),
                        CASE COALESCE(m."CarryPriceSource", 'Internal')
                            WHEN 'Nedco' THEN NULLIF(m."NedcoPrice", 0)
                            WHEN 'Gescan' THEN NULLIF(m."GescanPrice", 0)
                            WHEN 'Eecol' THEN NULLIF(m."EecolPrice", 0)
                            WHEN 'Guillevin' THEN NULLIF(m."GuillevinPrice", 0)
                            ELSE NULLIF(m."InternalPrice", 0)
                        END,
                        0
                    ),
                    0
                ) AS "LineTotal"
            FROM "PurchaseOrderItem" poi
            LEFT JOIN "EstimateMaterial" em ON poi."MaterialID" = em."EstimateMaterialID"
            LEFT JOIN "Material" m ON poi."CatalogItemID" = m."ItemID"
            WHERE poi."PurchaseOrderID" = %s
            ORDER BY "POItemID" ASC
        ''', (po_id,))
        return cur.fetchall()
    finally:
        conn.close()

def update_purchase_order_status(po_id: int, status: str):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            'UPDATE "PurchaseOrder" SET "Status" = %s WHERE "PurchaseOrderID" = %s',
            (status, po_id)
        )
        conn.commit()
    finally:
        conn.close()

def set_purchase_order_docx_path(po_id: int, docx_path: str):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            'UPDATE "PurchaseOrder" SET "ShippingDocuments" = %s WHERE "PurchaseOrderID" = %s',
            (docx_path, po_id)
        )
        conn.commit()
    finally:
        conn.close()


def archive_purchase_order_docx(po_id: int):
    """Builds and archives the PO DOCX into the project Purchase Orders folder."""
    from neon_ai.database.estimates import get_estimate_id_from_wo
    from neon_ai.database.folders import get_target_folder
    from neon_ai.purchase_order_generator import generate_po_docx

    data = get_po_export_data(po_id)
    if not data:
        raise ValueError(f"Purchase Order #{po_id} was not found.")

    items = get_po_items(po_id)
    export_items = [
        {
            "qty": item["QuantityOrdered"],
            "desc": item["Description"],
            "price": item["UnitPriceAtOrder"],
        }
        for item in items
    ]
    target_dir = get_target_folder(
        data.get("StreetNumber"),
        data.get("StreetName"),
        data.get("SiteName"),
        get_estimate_id_from_wo(data["WorkOrderID"]),
        "Purchase Orders",
    )
    safe_vendor = str(data.get("VendorName") or "Vendor").replace("/", "-").replace("\\", "-")
    path = os.path.join(target_dir, f"PO_{po_id}_{safe_vendor}.docx").replace("\\", "/")
    generate_po_docx(data, export_items, save_path=path)
    set_purchase_order_docx_path(po_id, path)
    return path

def get_purchase_order_status(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            'SELECT "Status" FROM "PurchaseOrder" WHERE "PurchaseOrderID" = %s',
            (po_id,)
        )
        row = cur.fetchone()
        return row["Status"] if row else None
    finally:
        conn.close()

def get_existing_po_details(work_order_id: int, vendor_id: int):
    """Returns the most recent non-retired PO for a WO/vendor pair."""
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT "PurchaseOrderID", "Status", "ShippingDocuments"
            FROM "PurchaseOrder"
            WHERE "WorkOrderID" = %s AND "VendorID" = %s AND "Status" NOT IN ('Retired', 'Draft')
            ORDER BY "PurchaseOrderID" DESC LIMIT 1
        ''', (work_order_id, vendor_id))
        return cur.fetchone()
    finally:
        conn.close()


def get_purchase_order_edit_items(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute(
            '''
            SELECT
                poi."POItemID",
                poi."MaterialID",
                poi."CatalogItemID",
                COALESCE(poi."Description", em."Description", m."Description") AS "Description",
                COALESCE(poi."QuantityOrdered", 0) AS "QuantityOrdered",
                COALESCE(poi."UnitPriceAtOrder", 0) AS "UnitPriceAtOrder",
                COALESCE(m."PartNumber", em."PartNumber", '') AS "PartNumber"
            FROM "PurchaseOrderItem" poi
            LEFT JOIN "EstimateMaterial" em ON poi."MaterialID" = em."EstimateMaterialID"
            LEFT JOIN "Material" m ON poi."CatalogItemID" = m."ItemID"
            WHERE poi."PurchaseOrderID" = %s
            ORDER BY poi."POItemID" ASC
            ''',
            (po_id,),
        )
        return cur.fetchall()
    finally:
        conn.close()


def get_purchase_order_for_material_request(po_id: int):
    return get_po_export_data(po_id)


def get_purchase_order_items_for_material_request(po_id: int):
    rows = get_purchase_order_edit_items(po_id)
    for row in rows:
        row["Notes"] = row.get("Notes") or ""
    return rows

def get_purchase_orders_ready_to_send():
    """Finds locked POs that already have a DOCX archived and are waiting to email."""
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT
                po."PurchaseOrderID",
                po."WorkOrderID",
                po."VendorID",
                po."ShippingDocuments",
                po."ExpectedArrivalDate",
                po."ExpectedArrivalNote",
                po."Date",
                v."VendorName",
                wo."SourceEstimateID" AS "EstimateID",
                s."SiteName",
                s."StreetNumber",
                s."StreetName"
            FROM "PurchaseOrder" po
            JOIN "Vendor" v ON po."VendorID" = v."VendorID"
            LEFT JOIN "WorkOrder" wo ON po."WorkOrderID" = wo."WorkOrderID"
            LEFT JOIN "Site" s ON wo."SiteID" = s."SiteID"
            WHERE po."Status" = 'Locked'
              AND COALESCE(po."ShippingDocuments", '') != ''
              AND po."Date" >= %s
            ORDER BY po."PurchaseOrderID" ASC
        ''', (AUTOMATION_MIN_DATE,))
        return cur.fetchall()
    finally:
        conn.close()

def get_vendor_email_for_po(po_id: int):
    """
    Uses the RFQ dispatch log as the persistent memory for the vendor recipient email.
    """
    from neon_ai.database.rfq import load_rfq_dispatch_log
    from neon_ai.database.vendors import ensure_vendor_schema

    ensure_vendor_schema()

    po_data = get_po_export_data(po_id)
    if not po_data:
        return None

    estimate_id = po_data.get("EstimateID")
    vendor_id = po_data.get("VendorID")
    entries = load_rfq_dispatch_log()
    matches = [
        row for row in entries
        if row.get("estimate_id") == estimate_id and row.get("vendor_id") == vendor_id
    ]
    if not matches:
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        try:
            cur.execute(
                '''
                SELECT COALESCE(vc."Email", '') AS "Email"
                FROM "PurchaseOrder" po
                JOIN "Vendor" v ON po."VendorID" = v."VendorID"
                LEFT JOIN public."VendorContact" vc ON vc."VendorID" = v."VendorID"
                WHERE po."PurchaseOrderID" = %s
                ORDER BY vc."VendorContactID" ASC
                LIMIT 1
                ''',
                (po_id,),
            )
            row = cur.fetchone()
            return ((row.get("Email") or "").strip().lower() or None) if row else None
        finally:
            conn.close()
    matches.sort(key=lambda row: row.get("sent_at", ""), reverse=True)
    return matches[0].get("recipient_email")


def get_work_order_procurement_state(work_order_id: int):
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute(
            '''
            SELECT
                w."WorkOrderID",
                COALESCE(NULLIF(TRIM(w."JobStatus"), ''), CASE WHEN COALESCE(w."IsClosed", FALSE) THEN 'Closed' ELSE 'Unknown' END) AS "JobStatus",
                COALESCE(w."IsClosed", FALSE) AS "IsClosed",
                COALESCE(s."SiteName", '') AS "SiteName"
            FROM "WorkOrder" w
            LEFT JOIN "Site" s ON w."SiteID" = s."SiteID"
            WHERE w."WorkOrderID" = %s
            ''',
            (work_order_id,),
        )
        return cur.fetchone()
    finally:
        conn.close()


def validate_work_order_for_purchase_order(work_order_id: int):
    state = get_work_order_procurement_state(work_order_id)
    if not state:
        raise ValueError(
            "Cannot create this purchase order because no matching work order exists. "
            "Solution: create the work order from the approved estimate first, then order materials."
        )

    status_text = str(state.get("JobStatus") or "").strip()
    is_open = status_text.upper() == "OPEN" and not bool(state.get("IsClosed"))
    if is_open:
        return state

    raise ValueError(
        f"Cannot create this purchase order because Work Order #{work_order_id} is not open "
        f"(current status: {status_text or 'Unknown'}). Solution: reopen the work order or create a new open work order before ordering materials."
    )


def set_purchase_order_expected_arrival(po_id: int, expected_date=None, expected_note: str = None):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            '''
            UPDATE "PurchaseOrder"
            SET "ExpectedArrivalDate" = %s,
                "ExpectedArrivalNote" = %s
            WHERE "PurchaseOrderID" = %s
            ''',
            (expected_date, expected_note[:255] if expected_note else None, po_id),
        )
        conn.commit()
    finally:
        conn.close()


def extract_po_id_from_text(subject="", body=""):
    text = f"{subject or ''}\n{body or ''}"
    match = re.search(r'\bpo\s*#?\s*(\d+)\b', text, re.IGNORECASE)
    return int(match.group(1)) if match else None


def find_matching_po_for_email(sender_email, subject="", body=""):
    po_id = extract_po_id_from_text(subject, body)
    if po_id:
        return po_id

    combined = f"{subject or ''}\n{body or ''}".lower()
    po_keywords = ("purchase order", " po ", "eta", "lead time", "ship", "shipment", "backorder")
    if not any(keyword in combined for keyword in po_keywords):
        return None

    sender = (sender_email or "").strip().lower()
    if not sender:
        return None

    matches = [
        row for row in load_po_dispatch_log()
        if (row.get("recipient_email") or "").strip().lower() == sender
    ]
    if not matches:
        return None
    matches.sort(key=lambda row: row.get("sent_at", ""), reverse=True)
    return matches[0].get("po_id")


def extract_eta_text(subject="", body_text=""):
    combined = f"{subject or ''}\n{body_text or ''}"
    sentences = re.split(r'(?<=[.!?])\s+|\n+', combined)
    best_sentence = None
    best_score = 0
    for sentence in sentences:
        lowered = sentence.lower().strip()
        if not lowered:
            continue

        score = 0
        if re.search(r'\beta\b', lowered):
            score += 5
        if re.search(r'\barriv|\blead time\b', lowered):
            score += 4
        if re.search(r'\bship|\bdelivery\b', lowered):
            score += 2
        if re.search(r'\bnext week\b|\btomorrow\b|\bthis week\b|\bby\s+[A-Za-z]+\b|\bin\s+\d+\s+(day|days|week|weeks)\b|\b\d+\s*(business )?(day|days|week|weeks)\b', lowered):
            score += 4
        if re.search(r'\b20\d{2}-\d{1,2}-\d{1,2}\b', sentence):
            score += 6
        if re.search(r'\b(january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2}\b', lowered):
            score += 5
        if score > best_score:
            best_sentence = sentence.strip()[:255]
            best_score = score
    if best_score > 0:
        return best_sentence
    return None


def parse_eta_date(eta_text: str, reference_date=None):
    if not eta_text:
        return None

    reference_date = reference_date or datetime.date.today()
    lowered = eta_text.lower()

    iso_match = re.search(r'\b(20\d{2})-(\d{1,2})-(\d{1,2})\b', eta_text)
    if iso_match:
        year, month, day = map(int, iso_match.groups())
        return datetime.date(year, month, day)

    md_match = re.search(r'\b(january|february|march|april|may|june|july|august|september|october|november|december)\s+(\d{1,2})(?:st|nd|rd|th)?\b', lowered)
    if md_match:
        month_name, day_value = md_match.groups()
        month = datetime.datetime.strptime(month_name.title(), "%B").month
        year = reference_date.year
        parsed = datetime.date(year, month, int(day_value))
        if parsed < reference_date:
            parsed = datetime.date(year + 1, month, int(day_value))
        return parsed

    if "tomorrow" in lowered:
        return reference_date + datetime.timedelta(days=1)
    if "next week" in lowered:
        return reference_date + datetime.timedelta(days=7)
    if "this week" in lowered:
        return reference_date + datetime.timedelta(days=3)

    in_match = re.search(r'\bin\s+(\d+)\s+(day|days|week|weeks)\b', lowered)
    if in_match:
        qty = int(in_match.group(1))
        unit = in_match.group(2)
        return reference_date + datetime.timedelta(days=qty * (7 if "week" in unit else 1))

    qty_match = re.search(r'\b(\d+)\s*(business\s+)?(day|days|week|weeks)\b', lowered)
    if qty_match:
        qty = int(qty_match.group(1))
        unit = qty_match.group(3)
        days = qty * (7 if "week" in unit else 1)
        return reference_date + datetime.timedelta(days=days)

    weekdays = {
        "monday": 0,
        "tuesday": 1,
        "wednesday": 2,
        "thursday": 3,
        "friday": 4,
        "saturday": 5,
        "sunday": 6,
    }
    for name, index in weekdays.items():
        if re.search(rf'\b{name}\b', lowered):
            delta = (index - reference_date.weekday()) % 7
            delta = 7 if delta == 0 else delta
            return reference_date + datetime.timedelta(days=delta)

    return None


def is_long_lead_eta(eta_date, sent_at=None):
    if not eta_date:
        return False
    if isinstance(sent_at, str):
        try:
            sent_at = datetime.datetime.fromisoformat(sent_at)
        except ValueError:
            sent_at = None
    sent_date = sent_at.date() if isinstance(sent_at, datetime.datetime) else datetime.date.today()
    return (eta_date - sent_date).days > 7


def po_has_any_packing_slip(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('''
            SELECT 1
            FROM "PurchaseOrderItem"
            WHERE "PurchaseOrderID" = %s
              AND COALESCE("LastPackingSlip", '') != ''
            LIMIT 1
        ''', (po_id,))
        return cur.fetchone() is not None
    finally:
        conn.close()


def po_is_fully_received(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('''
            SELECT COUNT(*) AS "Outstanding"
            FROM "PurchaseOrderItem"
            WHERE "PurchaseOrderID" = %s
              AND COALESCE("QuantityReceived", 0) < COALESCE("QuantityOrdered", 0)
        ''', (po_id,))
        row = cur.fetchone()
        return int(row["Outstanding"] or 0) == 0
    finally:
        conn.close()


def _normalize_text(value: str) -> str:
    return re.sub(r'[^a-z0-9]+', ' ', str(value or '').lower()).strip()


def _extract_numeric_values(text: str):
    values = []
    for match in re.findall(r'\b\d+(?:\.\d+)?\b', text or ''):
        try:
            values.append(float(match))
        except ValueError:
            continue
    return values


def infer_packing_slip_number(subject="", body="", attachment_path=None):
    text = "\n".join(part for part in [subject, body, os.path.basename(attachment_path) if attachment_path else ""] if part)
    match = re.search(r'\b(?:packing\s*slip|slip|ps)\s*#?\s*([A-Za-z0-9._-]+)\b', text, re.IGNORECASE)
    if match:
        return match.group(1)[:80]
    if attachment_path:
        return os.path.splitext(os.path.basename(attachment_path))[0][:80]
    return f"EMAIL-{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"


def get_po_receipt_items(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT
                "POItemID",
                "Description",
                "QuantityOrdered",
                COALESCE("QuantityReceived", 0) AS "QuantityReceived",
                ("QuantityOrdered" - COALESCE("QuantityReceived", 0)) AS "Remaining"
            FROM "PurchaseOrderItem"
            WHERE "PurchaseOrderID" = %s
            ORDER BY "POItemID" ASC
        ''', (po_id,))
        return cur.fetchall()
    finally:
        conn.close()


def split_receipt_refs(raw_refs: str):
    parts = []
    for chunk in str(raw_refs or "").split("|"):
        ref = chunk.strip()
        if ref and ref not in parts:
            parts.append(ref)
    return parts


def _get_or_create_purchase_order_receipt(cur, po_id: int, document_ref: str, receive_date: str, document_type: str = "Packing Slip"):
    cur.execute(
        '''
        SELECT "ReceiptID"
        FROM public."PurchaseOrderReceipt"
        WHERE "PurchaseOrderID" = %s
          AND LOWER(TRIM(COALESCE("DocumentRef", ''))) = LOWER(TRIM(COALESCE(%s, '')))
        ORDER BY "ReceiptID" DESC
        LIMIT 1
        ''',
        (po_id, document_ref),
    )
    existing = cur.fetchone()
    if existing and existing.get("ReceiptID"):
        cur.execute(
            '''
            UPDATE public."PurchaseOrderReceipt"
            SET "ReceiveDate" = COALESCE(%s, "ReceiveDate"),
                "DocumentType" = COALESCE(%s, "DocumentType")
            WHERE "ReceiptID" = %s
            ''',
            (receive_date or None, document_type or None, existing["ReceiptID"]),
        )
        return int(existing["ReceiptID"])

    cur.execute(
        '''
        INSERT INTO public."PurchaseOrderReceipt"
        ("PurchaseOrderID", "DocumentType", "DocumentRef", "ReceiveDate")
        VALUES (%s, %s, %s, %s)
        RETURNING "ReceiptID"
        ''',
        (po_id, document_type or "Packing Slip", document_ref, receive_date or None),
    )
    row = cur.fetchone()
    return int(row["ReceiptID"])


def get_purchase_order_receipt_choices(po_id: int):
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute(
            '''
            SELECT
                pr."ReceiptID",
                COALESCE(pr."DocumentType", 'Packing Slip') AS "DocumentType",
                COALESCE(pr."DocumentRef", '') AS "DocumentRef",
                pr."ReceiveDate",
                COUNT(pri."ReceiptItemID") AS "LineCount",
                COALESCE(SUM(pri."QuantityReceived"), 0) AS "TotalQty"
            FROM public."PurchaseOrderReceipt" pr
            LEFT JOIN public."PurchaseOrderReceiptItem" pri ON pri."ReceiptID" = pr."ReceiptID"
            WHERE pr."PurchaseOrderID" = %s
            GROUP BY pr."ReceiptID", pr."DocumentType", pr."DocumentRef", pr."ReceiveDate"
            ORDER BY COALESCE(pr."ReceiveDate"::text, '') DESC, pr."ReceiptID" DESC
            ''',
            (po_id,),
        )
        db_rows = cur.fetchall()

        cur.execute(
            '''
            SELECT DISTINCT COALESCE("LastPackingSlip", '') AS "DocumentRef"
            FROM "PurchaseOrderItem"
            WHERE "PurchaseOrderID" = %s
              AND COALESCE("LastPackingSlip", '') != ''
            ''',
            (po_id,),
        )
        legacy_rows = cur.fetchall()
    finally:
        conn.close()

    choices = []
    seen_refs = set()
    for row in db_rows:
        ref = str(row.get("DocumentRef") or "").strip()
        if ref:
            seen_refs.add(ref.lower())
        receive_date = row.get("ReceiveDate")
        date_text = receive_date.isoformat() if hasattr(receive_date, "isoformat") else (receive_date or "Unknown Date")
        choices.append(
            {
                "Key": f"receipt:{int(row['ReceiptID'])}",
                "ReceiptID": int(row["ReceiptID"]),
                "DocumentRef": ref,
                "DocumentType": row.get("DocumentType") or "Packing Slip",
                "ReceiveDate": date_text,
                "Source": "ledger",
                "Label": f"{row.get('DocumentType') or 'Packing Slip'} {ref or '(no ref)'} | {date_text} | {int(float(row.get('LineCount') or 0))} line(s)",
            }
        )

    for row in legacy_rows:
        for ref in split_receipt_refs(row.get("DocumentRef")):
            if ref.lower() in seen_refs:
                continue
            seen_refs.add(ref.lower())
            choices.append(
                {
                    "Key": f"legacy:{ref}",
                    "ReceiptID": None,
                    "DocumentRef": ref,
                    "DocumentType": "Legacy Receipt",
                    "ReceiveDate": "",
                    "Source": "legacy",
                    "Label": f"Legacy receipt {ref}",
                }
            )

    choices.append(
        {
            "Key": "all_received",
            "ReceiptID": None,
            "DocumentRef": "All received material",
            "DocumentType": "All Received",
            "ReceiveDate": "",
            "Source": "aggregate",
            "Label": "All received material on this PO",
        }
    )
    return choices


def get_purchase_order_receipt_quantities(po_id: int, receipt_key: str):
    ensure_purchase_schema()
    key = str(receipt_key or "").strip()
    if not key or key == "all_received":
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        try:
            cur.execute(
                '''
                SELECT "POItemID", COALESCE("QuantityReceived", 0) AS "Qty"
                FROM "PurchaseOrderItem"
                WHERE "PurchaseOrderID" = %s
                ''',
                (po_id,),
            )
            rows = cur.fetchall()
        finally:
            conn.close()
        return {int(row["POItemID"]): float(row.get("Qty") or 0) for row in rows}

    if key.startswith("receipt:"):
        receipt_id = int(key.split(":", 1)[1])
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        try:
            cur.execute(
                '''
                SELECT "POItemID", COALESCE("QuantityReceived", 0) AS "Qty"
                FROM public."PurchaseOrderReceiptItem"
                WHERE "ReceiptID" = %s
                ''',
                (receipt_id,),
            )
            rows = cur.fetchall()
        finally:
            conn.close()
        return {int(row["POItemID"]): float(row.get("Qty") or 0) for row in rows}

    if key.startswith("legacy:"):
        ref = key.split(":", 1)[1].strip().lower()
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        try:
            cur.execute(
                '''
                SELECT "POItemID", COALESCE("QuantityReceived", 0) AS "Qty", COALESCE("LastPackingSlip", '') AS "LastPackingSlip"
                FROM "PurchaseOrderItem"
                WHERE "PurchaseOrderID" = %s
                ''',
                (po_id,),
            )
            rows = cur.fetchall()
        finally:
            conn.close()

        quantities = {}
        for row in rows:
            refs = [item.lower() for item in split_receipt_refs(row.get("LastPackingSlip"))]
            if ref in refs:
                quantities[int(row["POItemID"])] = float(row.get("Qty") or 0)
        return quantities

    return {}


def _match_po_item_to_line(line: str, po_items: list):
    normalized_line = _normalize_text(line)
    if not normalized_line:
        return None

    best_item = None
    best_score = 0
    for item in po_items:
        description = item.get("Description") or ""
        normalized_desc = _normalize_text(description)
        if not normalized_desc:
            continue
        if normalized_desc in normalized_line:
            score = len(normalized_desc.split()) + 5
        else:
            desc_tokens = [tok for tok in normalized_desc.split() if len(tok) > 2]
            score = sum(1 for tok in desc_tokens if tok in normalized_line)
        if score > best_score:
            best_item = item
            best_score = score

    return best_item if best_score >= 2 else None


def parse_po_receipt_text(po_id: int, text: str, assume_received: bool = False):
    po_items = get_po_receipt_items(po_id)
    if not po_items:
        return {"received": [], "backordered": []}

    received = []
    backordered = []
    mode = "received" if assume_received else None

    for raw_line in (text or "").splitlines():
        line = raw_line.strip()
        lowered = line.lower()
        if not line:
            continue

        if any(marker in lowered for marker in ("received:", "arrived:", "picked up:", "on hand:")):
            mode = "received"
            continue
        if any(marker in lowered for marker in ("backordered:", "back ordered:", "remaining:", "short:")):
            mode = "backordered"
            continue

        item = _match_po_item_to_line(line, po_items)
        if not item:
            continue

        line_is_backordered = mode == "backordered" or ("backorder" in lowered or "back order" in lowered)
        line_is_received = mode == "received" or assume_received or any(
            token in lowered for token in ("received", "arrived", "picked up", "included", "shipped")
        )

        qty_values = _extract_numeric_values(line)
        remaining = float(item.get("Remaining") or 0)
        qty = qty_values[0] if qty_values else (remaining if line_is_received else 0)
        qty = max(0.0, min(float(qty), remaining))

        if line_is_backordered:
            backordered.append({"po_item_id": item["POItemID"], "description": item["Description"], "line": line})
        elif line_is_received and qty > 0:
            received.append((item["POItemID"], qty))

    deduped_received = {}
    for po_item_id, qty in received:
        deduped_received[po_item_id] = max(deduped_received.get(po_item_id, 0), qty)

    return {
        "received": [(po_item_id, qty) for po_item_id, qty in deduped_received.items()],
        "backordered": backordered,
    }


def update_purchase_order_receiving_status(po_id: int):
    ensure_purchase_schema()
    if po_is_fully_received(po_id):
        update_purchase_order_status(po_id, "FullyReceived")
        return "FullyReceived"

    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('''
            SELECT 1
            FROM "PurchaseOrderItem"
            WHERE "PurchaseOrderID" = %s
              AND COALESCE("QuantityReceived", 0) > 0
            LIMIT 1
        ''', (po_id,))
        has_received = cur.fetchone() is not None
    finally:
        conn.close()

    if has_received:
        update_purchase_order_status(po_id, "BackOrdered")
        return "BackOrdered"
    return get_purchase_order_status(po_id)


def get_po_followup_status(po_id: int):
    started_at = time.perf_counter()
    try:
        po_data = get_po_export_data(po_id)
        record = next((row for row in load_po_dispatch_log() if row.get("po_id") == po_id), {})
        eta_date_value = po_data.get("ExpectedArrivalDate") if po_data else None
        eta_note_value = po_data.get("ExpectedArrivalNote") if po_data else None
        status = {
            "po_status": po_data.get("Status") if po_data else None,
            "eta_text": eta_note_value or record.get("eta_text"),
            "eta_date": (eta_date_value.isoformat() if hasattr(eta_date_value, "isoformat") else eta_date_value) or record.get("eta_date"),
            "weekly_followup_active": bool(record.get("long_lead")) and not po_has_any_packing_slip(po_id) and not po_is_fully_received(po_id) and (po_data.get("Status") != "ReadyForPickup" if po_data else True),
            "next_followup": None,
            "sent_at": record.get("sent_at"),
            "ready_for_pickup_at": record.get("ready_for_pickup_at"),
            "last_weekly_followup_sent_at": record.get("last_weekly_followup_sent_at"),
            "eta_followup_sent_at": record.get("eta_followup_sent_at"),
            "recipient_email": record.get("recipient_email"),
        }

        if po_has_any_packing_slip(po_id) or po_is_fully_received(po_id):
            status["next_followup"] = "None - receipt logged"
            status["weekly_followup_active"] = False
            return status

        if record.get("ready_for_pickup_at"):
            status["next_followup"] = "Owner pickup pending"
            status["weekly_followup_active"] = False
            return status

        eta_date_raw = record.get("eta_date")
        if eta_date_raw:
            try:
                eta_date = datetime.date.fromisoformat(eta_date_raw)
                status["next_followup"] = str(eta_date + datetime.timedelta(days=1))
            except ValueError:
                pass

        if status["weekly_followup_active"]:
            last_weekly = record.get("last_weekly_followup_sent_at")
            if last_weekly:
                try:
                    next_weekly = datetime.datetime.fromisoformat(last_weekly).date() + datetime.timedelta(days=7)
                    status["next_followup"] = str(next_weekly)
                except ValueError:
                    pass
            elif record.get("sent_at"):
                try:
                    next_weekly = datetime.datetime.fromisoformat(record["sent_at"]).date() + datetime.timedelta(days=7)
                    status["next_followup"] = str(next_weekly)
                except ValueError:
                    pass

        return status
    finally:
        _perf_log("db", "purchases.get_po_followup_status", started_at)


def get_backordered_purchase_orders():
    ensure_purchase_schema()
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT
                po."PurchaseOrderID",
                po."Date",
                po."Status",
                po."ExpectedArrivalDate",
                v."VendorName",
                s."SiteName",
                COUNT(*) FILTER (
                    WHERE COALESCE(poi."QuantityReceived", 0) < COALESCE(poi."QuantityOrdered", 0)
                ) AS "BackorderedLineCount"
            FROM "PurchaseOrder" po
            JOIN "Vendor" v ON po."VendorID" = v."VendorID"
            LEFT JOIN "WorkOrder" wo ON po."WorkOrderID" = wo."WorkOrderID"
            LEFT JOIN "Site" s ON wo."SiteID" = s."SiteID"
            JOIN "PurchaseOrderItem" poi ON poi."PurchaseOrderID" = po."PurchaseOrderID"
            WHERE po."Date" >= %s
            GROUP BY po."PurchaseOrderID", po."Date", po."Status", po."ExpectedArrivalDate", v."VendorName", s."SiteName"
            HAVING COUNT(*) FILTER (
                WHERE COALESCE(poi."QuantityReceived", 0) < COALESCE(poi."QuantityOrdered", 0)
            ) > 0
               AND COALESCE(SUM(COALESCE(poi."QuantityReceived", 0)), 0) > 0
            ORDER BY po."Date" ASC, po."PurchaseOrderID" ASC
        ''', (AUTOMATION_MIN_DATE,))
        return cur.fetchall()
    finally:
        conn.close()


def sweep_for_backordered_purchase_orders():
    from neon_ai.gateway import MY_EMAIL, send_to_user
    from neon_ai.database.automation import log_estimate_action

    today = datetime.date.today()
    if today < AUTOMATION_MIN_DATE:
        return

    for po in get_backordered_purchase_orders():
        po_id = po["PurchaseOrderID"]
        po_status = po.get("Status") or ""
        if po_status not in ("BackOrdered", "PartialReceived", "ReadyForPickup", "Sent"):
            update_purchase_order_status(po_id, "BackOrdered")

        record = next((row for row in load_po_dispatch_log() if row.get("po_id") == po_id), {})
        last_alert_raw = record.get("last_backorder_alert_at")
        last_alert = None
        if last_alert_raw:
            try:
                last_alert = datetime.datetime.fromisoformat(last_alert_raw)
            except ValueError:
                last_alert = None

        if last_alert and today < last_alert.date() + datetime.timedelta(days=7):
            continue

        send_to_user(
            subject=f"Backordered Parts Review: PO #{po_id}",
            content=(
                f"PO #{po_id} still has backordered material that needs attention.\n\n"
                f"Vendor: {po['VendorName']}\n"
                f"Site: {po.get('SiteName') or 'N/A'}\n"
                f"PO Date: {po.get('Date')}\n"
                f"Outstanding lines: {po.get('BackorderedLineCount')}\n"
                f"Current PO status: {po.get('Status')}\n\n"
                "Next action: review outstanding backordered parts and decide whether to follow up, substitute, or split-order the remaining material."
            )
        )
        update_payload = {"last_backorder_alert_at": datetime.datetime.now().isoformat()}

        recipient_email = record.get("recipient_email") or get_vendor_email_for_po(po_id)
        last_vendor_followup_raw = record.get("last_backorder_vendor_followup_at")
        last_vendor_followup = None
        if last_vendor_followup_raw:
            try:
                last_vendor_followup = datetime.datetime.fromisoformat(last_vendor_followup_raw)
            except ValueError:
                last_vendor_followup = None

        if recipient_email and (last_vendor_followup is None or today >= last_vendor_followup.date() + datetime.timedelta(days=7)):
            if not _background_vendor_po_followups_enabled():
                print(
                    "PO Sweeper: Background vendor follow-up is disabled. "
                    "Use manual PO follow-up/send workflow. "
                    f"PO #{po_id} for {po['VendorName']} needs manual backorder follow-up."
                )
            else:
                sent = send_to_user(
                    subject=f"Backorder ETA Request: PO #{po_id}",
                    content=(
                        f"Hello {po['VendorName']},\n\n"
                        f"We have received the first delivery for Purchase Order #{po_id}, but there are still outstanding backordered items for {po.get('SiteName') or 'the project'}.\n\n"
                        "Please let us know the expected arrival date for the remaining material and advise if there are any supply issues we should plan around.\n\n"
                        "Thank you,\nArgon Electrical"
                    ),
                    recipient=recipient_email,
                    cc_recipients=[MY_EMAIL]
                )
                if sent:
                    update_payload["last_backorder_vendor_followup_at"] = datetime.datetime.now().isoformat()

        upsert_po_dispatch_record(po_id, update_payload)

        po_data = get_po_export_data(po_id)
        estimate_id = po_data.get("EstimateID") if po_data else None
        if estimate_id:
            log_estimate_action(
                estimate_id,
                f"Weekly backorder review reminder sent for PO #{po_id}. Outstanding lines: {po.get('BackorderedLineCount')}.",
                "Purchase Order"
            )

def _legacy_po_auto_send_enabled() -> bool:
    return str(os.getenv(LEGACY_PO_AUTO_SEND_ENV, "0")).strip().lower() in {"1", "true", "yes", "on"}


def _run_legacy_locked_purchase_order_auto_send():
    """Legacy vendor-send behavior retained only behind an explicit env gate."""
    from neon_ai.gateway import MY_EMAIL, send_to_user
    from neon_ai.database.automation import log_estimate_action
    from neon_ai.purchase_order_generator import convert_docx_to_pdf

    pending = get_purchase_orders_ready_to_send()
    if not pending:
        return

    for po in pending:
        po_id = po["PurchaseOrderID"]
        docx_path = po.get("ShippingDocuments")
        if not docx_path or not os.path.exists(docx_path):
            continue

        recipient_email = get_vendor_email_for_po(po_id)
        if not recipient_email:
            print(f"PO Sweeper: No vendor email found for PO #{po_id}.")
            continue

        attachment_path = docx_path
        pdf_path = None
        try:
            pdf_path = convert_docx_to_pdf(docx_path)
            attachment_path = pdf_path
        except Exception as exc:
            print(f"PO Sweeper: PDF conversion failed for PO #{po_id}: {exc}. Falling back to DOCX attachment.")

        sent = send_to_user(
            subject=f"Purchase Order #{po_id} - {po['SiteName']}",
            content=(
                f"Hello {po['VendorName']},\n\n"
                f"Please find attached Purchase Order #{po_id} for {po['SiteName']}.\n\n"
                "Please confirm receipt, advise on any issues or substitutions, and let us know the expected ETA for the parts.\n\n"
                "Thank you,\nArgon Electrical"
            ),
            recipient=recipient_email,
            attachment_path=attachment_path,
            cc_recipients=[MY_EMAIL]
        )
        if not sent:
            continue

        upsert_po_dispatch_record(po_id, {
            "recipient_email": recipient_email.lower(),
            "vendor_name": po["VendorName"],
            "estimate_id": po.get("EstimateID"),
            "site_name": po.get("SiteName"),
            "sent_at": datetime.datetime.now().isoformat(),
            "status": "Sent",
            "docx_path": docx_path,
            "pdf_path": pdf_path,
        })
        update_purchase_order_status(po_id, "Sent")
        estimate_id = po.get("EstimateID")
        if estimate_id:
            log_estimate_action(
                estimate_id,
                f"Purchase Order #{po_id} emailed to {po['VendorName']} at {recipient_email} with owner CC. Attachment: {attachment_path}",
                "Purchase Order"
            )


def sweep_for_locked_purchase_orders():
    """Fence legacy PO auto-send so locked purchase orders require explicit manual send."""
    if _legacy_po_auto_send_enabled():
        print(
            f"PO Sweeper: {LEGACY_PO_AUTO_SEND_ENV}=1 detected. "
            "Running legacy PO auto-send behavior."
        )
        _run_legacy_locked_purchase_order_auto_send()
        return

    pending = get_purchase_orders_ready_to_send()
    if not pending:
        print("PO Sweeper: No locked purchase orders ready to send.")
        return

    print(
        "PO Sweeper: Legacy PO auto-send is disabled. "
        "Use manual PO send/approval workflow. "
        f"Locked purchase orders pending manual send: {len(pending)}."
    )


def send_purchase_order_now(po_id: int):
    """Archives the DOCX if needed and sends the PO email immediately."""
    from neon_ai.gateway import MY_EMAIL, send_to_user
    from neon_ai.database.automation import log_estimate_action
    from neon_ai.purchase_order_generator import convert_docx_to_pdf

    po_data = get_po_export_data(po_id)
    if not po_data:
        raise ValueError(f"Purchase Order #{po_id} was not found.")

    docx_path = po_data.get("ShippingDocuments")
    if not docx_path or not os.path.exists(docx_path):
        docx_path = archive_purchase_order_docx(po_id)

    recipient_email = get_vendor_email_for_po(po_id)
    if not recipient_email:
        raise ValueError(
            f"Purchase Order #{po_id} does not have a vendor email on file yet. "
            "Solution: add a vendor contact email on the vendor record, or send an RFQ first if you want to reuse that recipient automatically."
        )

    attachment_path = docx_path
    pdf_path = None
    try:
        pdf_path = convert_docx_to_pdf(docx_path)
        attachment_path = pdf_path
    except Exception:
        pdf_path = None
    sent = send_to_user(
        subject=f"Purchase Order #{po_id} - {po_data.get('SiteName') or 'Project'}",
        content=(
            f"Hello {po_data.get('VendorName')},\n\n"
            f"Please find attached Purchase Order #{po_id} for {po_data.get('SiteName') or 'the project'}.\n\n"
            "Please confirm receipt, advise on any issues or substitutions, and let us know the expected ETA for the parts.\n\n"
            "Thank you,\nArgon Electrical"
        ),
        recipient=recipient_email,
        attachment_path=attachment_path,
        cc_recipients=[MY_EMAIL],
    )
    if not sent:
        raise RuntimeError(f"Purchase Order #{po_id} could not be sent through the email gateway.")

    mark_purchase_order_sent(
        po_id,
        recipient_email=recipient_email,
        vendor_name=po_data.get("VendorName"),
        estimate_id=po_data.get("EstimateID"),
        site_name=po_data.get("SiteName"),
        docx_path=docx_path,
        pdf_path=pdf_path,
        attachment_path=attachment_path,
    )

    return {
        "po_id": po_id,
        "recipient_email": recipient_email,
        "docx_path": docx_path,
        "pdf_path": pdf_path,
        "attachment_path": attachment_path,
        "status": "Sent",
    }


def mark_purchase_order_sent(
    po_id: int,
    *,
    recipient_email: str,
    vendor_name: str | None,
    estimate_id: int | None,
    site_name: str | None,
    docx_path: str | None,
    pdf_path: str | None,
    attachment_path: str | None,
) -> None:
    from neon_ai.database.automation import log_estimate_action

    upsert_po_dispatch_record(po_id, {
        "recipient_email": str(recipient_email or "").strip().lower(),
        "vendor_name": vendor_name,
        "estimate_id": estimate_id,
        "site_name": site_name,
        "sent_at": datetime.datetime.now().isoformat(),
        "status": "Sent",
        "docx_path": docx_path,
        "pdf_path": pdf_path,
    })
    update_purchase_order_status(po_id, "Sent")
    if estimate_id:
        log_estimate_action(
            estimate_id,
            f"Purchase Order #{po_id} emailed to {vendor_name or 'Vendor'} at {recipient_email}. Attachment: {attachment_path}",
            "Purchase Order"
        )


def process_inbound_vendor_po_email(po_id: int, sender_email: str, subject: str, body: str, attachment_path: str = None, received_at=None):
    """Processes ETA updates, ready-for-pickup notices, and receipt updates tied to a PO."""
    from neon_ai.database.automation import log_estimate_action
    from neon_ai.database.rfq import extract_text_from_attachment, ocr_pdf_attachment
    from neon_ai.gateway import send_to_user

    po_data = get_po_export_data(po_id)
    if not po_data:
        return None

    attachment_text = ""
    if attachment_path and os.path.exists(attachment_path):
        attachment_text = extract_text_from_attachment(attachment_path)
        if not attachment_text and attachment_path.lower().endswith(".pdf"):
            attachment_text = ocr_pdf_attachment(attachment_path)

    combined_text = "\n".join(part for part in [subject, body, attachment_text] if part)
    lowered = combined_text.lower()
    eta_text = extract_eta_text(subject, combined_text)
    reference_date = received_at.date() if hasattr(received_at, "date") else datetime.date.today()
    eta_date = parse_eta_date(eta_text, reference_date=reference_date)
    ready_for_pickup = any(
        phrase in lowered for phrase in (
            "ready for pickup",
            "ready to pick up",
            "available for pickup",
            "will call",
            "order is ready",
            "parts are ready",
        )
    )
    receipt_email = bool(attachment_path) or any(
        phrase in lowered for phrase in (
            "packing slip",
            "received",
            "backordered",
            "back ordered",
            "picked up",
        )
    )

    existing_record = next((row for row in load_po_dispatch_log() if row.get("po_id") == po_id), {})

    updates = {
        "last_vendor_reply_at": (received_at.isoformat() if hasattr(received_at, "isoformat") else datetime.datetime.now().isoformat()),
        "last_vendor_reply_subject": (subject or "")[:255],
    }
    if eta_text:
        updates["eta_text"] = eta_text
    if eta_date:
        updates["eta_date"] = eta_date.isoformat()
        updates["long_lead"] = is_long_lead_eta(eta_date, existing_record.get("sent_at"))
        updates["eta_followup_sent_at"] = None
        updates["last_weekly_followup_sent_at"] = None
    if ready_for_pickup:
        updates["ready_for_pickup_at"] = updates["last_vendor_reply_at"]
    receipt_result = None
    if receipt_email:
        receipt_result = parse_po_receipt_text(
            po_id,
            combined_text,
            assume_received=bool(attachment_path) or "packing slip" in lowered
        )
    if eta_text or eta_date:
        set_purchase_order_expected_arrival(po_id, eta_date.isoformat() if eta_date else None, eta_text)
    upsert_po_dispatch_record(po_id, updates)

    estimate_id = po_data.get("EstimateID")
    if ready_for_pickup and po_data.get("Date") and po_data["Date"] >= AUTOMATION_MIN_DATE:
        update_purchase_order_status(po_id, "ReadyForPickup")
        if not existing_record.get("ready_pickup_notified_at"):
            send_to_user(
                subject=f"Parts Ready For Pickup: PO #{po_id}",
                content=(
                    f"{po_data.get('VendorName')} says the parts for PO #{po_id} are ready for pickup.\n\n"
                    f"Site: {po_data.get('SiteName')}\n"
                    f"Vendor message: {eta_text or subject or 'See inbox thread.'}\n\n"
                    "Next action: pick up the parts and send the packing slip or receipt details back to the Argon inbox."
                )
            )
            upsert_po_dispatch_record(po_id, {"ready_pickup_notified_at": datetime.datetime.now().isoformat()})
        if estimate_id:
            log_estimate_action(
                estimate_id,
                f"Vendor marked PO #{po_id} ready for pickup. Owner notified to collect parts.",
                "Purchase Order"
            )

    if receipt_result and receipt_result["received"]:
        packing_slip = infer_packing_slip_number(subject, body, attachment_path)
        receive_date = reference_date.isoformat()
        log_material_receipt_batch(packing_slip, receive_date, receipt_result["received"])
        new_status = update_purchase_order_receiving_status(po_id)
        update_payload = {
            "last_receipt_at": datetime.datetime.now().isoformat(),
            "last_packing_slip": packing_slip,
        }
        if new_status == "FullyReceived":
            update_payload["long_lead"] = False
        upsert_po_dispatch_record(po_id, update_payload)
        if estimate_id:
            log_estimate_action(
                estimate_id,
                f"Email-driven receipt logged for PO #{po_id}. Packing slip {packing_slip}. Received lines: {len(receipt_result['received'])}. Status -> {new_status}.",
                "Purchase Order"
            )
        if receipt_result["backordered"] and estimate_id:
            backordered_text = "; ".join(item["description"] for item in receipt_result["backordered"][:5])
            log_estimate_action(
                estimate_id,
                f"PO #{po_id} still has backordered items after receipt: {backordered_text}",
                "Purchase Order"
            )
    elif receipt_result and receipt_result["backordered"] and estimate_id:
        backordered_text = "; ".join(item["description"] for item in receipt_result["backordered"][:5])
        log_estimate_action(
            estimate_id,
            f"PO #{po_id} email mentioned outstanding or backordered items, but no received quantities were parsed yet. The PO status was left unchanged until an initial delivery is logged. Outstanding lines: {backordered_text}",
            "Purchase Order"
        )

    if estimate_id:
        if eta_date:
            log_estimate_action(
                estimate_id,
                f"Vendor ETA received for PO #{po_id} from {sender_email}. ETA: {eta_date.isoformat()}. Detail: {eta_text or 'Not captured.'}",
                "Purchase Order"
            )
        else:
            log_estimate_action(
                estimate_id,
                f"Vendor replied to PO #{po_id} from {sender_email}, but no parseable ETA was found. Detail: {eta_text or 'No ETA sentence detected.'}",
                "Purchase Order"
            )

    return {
        "po_id": po_id,
        "estimate_id": estimate_id,
        "vendor_name": po_data.get("VendorName"),
        "site_name": po_data.get("SiteName"),
        "eta_text": eta_text,
        "eta_date": eta_date.isoformat() if eta_date else None,
        "long_lead": is_long_lead_eta(eta_date, existing_record.get("sent_at")) if eta_date else False,
        "ready_for_pickup": ready_for_pickup,
        "receipt_logged": bool(receipt_result and receipt_result["received"]),
        "received_count": len(receipt_result["received"]) if receipt_result else 0,
        "backordered_count": len(receipt_result["backordered"]) if receipt_result else 0,
    }


def sweep_for_po_eta_followups():
    """Handles owner reminders after ETA slips and weekly vendor check-ins for long-lead POs."""
    from neon_ai.gateway import MY_EMAIL, send_to_user
    from neon_ai.database.automation import log_estimate_action

    today = datetime.date.today()
    if today < AUTOMATION_MIN_DATE:
        return

    for record in load_po_dispatch_log():
        po_id = record.get("po_id")
        if not po_id:
            continue

        sent_at_raw = record.get("sent_at")
        try:
            sent_at = datetime.datetime.fromisoformat(sent_at_raw) if sent_at_raw else None
        except ValueError:
            sent_at = None
        if not sent_at or sent_at.date() < AUTOMATION_MIN_DATE:
            continue

        if po_has_any_packing_slip(po_id) or po_is_fully_received(po_id):
            continue

        po_data = get_po_export_data(po_id)
        if not po_data:
            continue
        if po_data.get("Status") == "ReadyForPickup":
            continue

        eta_date_raw = record.get("eta_date")
        eta_date = None
        if eta_date_raw:
            try:
                eta_date = datetime.date.fromisoformat(eta_date_raw)
            except ValueError:
                eta_date = None

        recipient_email = record.get("recipient_email") or get_vendor_email_for_po(po_id)
        estimate_id = po_data.get("EstimateID")

        if eta_date and today >= eta_date + datetime.timedelta(days=1):
            if not record.get("eta_followup_sent_at"):
                send_to_user(
                    subject=f"Packing Slip Follow-Up Needed: PO #{po_id}",
                    content=(
                        f"PO #{po_id} for {po_data.get('VendorName')} has reached the promised ETA window and no packing slip has been logged yet.\n\n"
                        f"Site: {po_data.get('SiteName')}\n"
                        f"ETA provided: {eta_date.isoformat()}\n"
                        f"Vendor ETA note: {record.get('eta_text') or 'None captured'}\n\n"
                        "Please follow up with the wholesaler."
                    )
                )
                record["eta_followup_sent_at"] = datetime.datetime.now().isoformat()
                if estimate_id:
                    log_estimate_action(
                        estimate_id,
                        f"24-hour post-ETA owner reminder sent for PO #{po_id}; no packing slip logged after ETA {eta_date.isoformat()}.",
                        "Purchase Order"
                    )

        if record.get("long_lead") and recipient_email:
            last_weekly_raw = record.get("last_weekly_followup_sent_at")
            last_weekly = None
            if last_weekly_raw:
                try:
                    last_weekly = datetime.datetime.fromisoformat(last_weekly_raw)
                except ValueError:
                    last_weekly = None

            if last_weekly is None or today >= last_weekly.date() + datetime.timedelta(days=7):
                if not _background_vendor_po_followups_enabled():
                    print(
                        "PO Sweeper: Background vendor follow-up is disabled. "
                        "Use manual PO follow-up/send workflow. "
                        f"PO #{po_id} for {po_data.get('VendorName')} needs manual weekly follow-up."
                    )
                else:
                    sent = send_to_user(
                        subject=f"Weekly Check-In: PO #{po_id}",
                        content=(
                            f"Hello {po_data.get('VendorName')},\n\n"
                            f"We are checking in on Purchase Order #{po_id} for {po_data.get('SiteName')}.\n\n"
                            "Please confirm the parts remain on order and share any updated ETA or shipment details.\n\n"
                            "Thank you,\nArgon Electrical"
                        ),
                        recipient=recipient_email,
                        cc_recipients=[MY_EMAIL]
                    )
                    if sent:
                        record["last_weekly_followup_sent_at"] = datetime.datetime.now().isoformat()
                        if estimate_id:
                            log_estimate_action(
                                estimate_id,
                                f"Weekly long-lead vendor follow-up sent for PO #{po_id} to {po_data.get('VendorName')}.",
                                "Purchase Order"
                            )

        upsert_po_dispatch_record(po_id, record)

# ==========================================
# 3. UTILITIES & CLEANUP
# ==========================================

def get_purchase_orders():
    started_at = time.perf_counter()
    try:
        ensure_purchase_schema()
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        try:
            cur.execute('''
                SELECT po."PurchaseOrderID", v."VendorName", po."WorkOrderID", po."Date", po."Status", po."PurchaseOrderTotal"
                FROM "PurchaseOrder" po
                JOIN "Vendor" v ON po."VendorID" = v."VendorID"
                WHERE po."Status" != 'Retired'
                ORDER BY po."PurchaseOrderID" DESC
            ''')
            return cur.fetchall()
        finally:
            conn.close()
    finally:
        _perf_log("db", "purchases.get_purchase_orders", started_at)

def get_next_po_id():
    conn = get_connection()
    cur = conn.cursor()
    cur.execute('SELECT MAX("PurchaseOrderID") FROM "PurchaseOrder"')
    res = cur.fetchone()[0]
    conn.close()
    return (res + 1) if res else 1

# ==========================================
# 4. BACKWARD COMPATIBILITY (The Shim)
# ==========================================

def insert_purchase_order(workorder_id, vendor_id, employee_id, total_amount, description, po_date):
    """
    LEGACY SHIM: Redirects old 'Private Brain' calls to the new PO engine.
    This prevents the app from crashing while we migrate to line-item logic.
    """
    # We call the new engine with an empty list of items for now
    return save_new_purchase_order(
        work_order_id=workorder_id, 
        items=[], 
        vendor_id=vendor_id)

def get_existing_po_id(work_order_id: int, vendor_id: int):
    """Checks if a Purchase Order already exists for this WO and Vendor combo."""
    from neon_ai.database.connection import get_connection
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute('''
            SELECT "PurchaseOrderID" 
            FROM "PurchaseOrder" 
            WHERE "WorkOrderID" = %s AND "VendorID" = %s AND "Status" != 'Retired'
            ORDER BY "PurchaseOrderID" DESC LIMIT 1
        ''', (work_order_id, vendor_id))
        res = cur.fetchone()
        return res[0] if res else None
    finally:
        conn.close()

def get_purchase_orders_for_pipeline():
    """Pulls the POs for the bottom-left Master Ledger."""
    started_at = time.perf_counter()
    try:
        ensure_purchase_schema()
        from neon_ai.database.connection import get_connection
        from psycopg2.extras import RealDictCursor
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        try:
            cur.execute('''
                SELECT po."PurchaseOrderID", po."WorkOrderID", s."SiteName", po."Date", po."Status"
                FROM "PurchaseOrder" po
                LEFT JOIN "WorkOrder" wo ON po."WorkOrderID" = wo."WorkOrderID"
                LEFT JOIN "Site" s ON wo."SiteID" = s."SiteID"
                ORDER BY po."PurchaseOrderID" DESC
            ''')
            return cur.fetchall()
        finally:
            conn.close()
    finally:
        _perf_log("db", "purchases.get_purchase_orders_for_pipeline", started_at)

def get_po_items_with_receiving(po_id: int):
    """Pulls items with Ordered vs Received math."""
    ensure_purchase_schema()
    from neon_ai.database.connection import get_connection
    from psycopg2.extras import RealDictCursor
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute('''
            SELECT 
                poi."POItemID",
                poi."MaterialID",
                poi."CatalogItemID",
                COALESCE(poi."Description", em."Description", m."Description") AS "Description",
                poi."QuantityOrdered",
                poi."QuantityReceived", 
                ("QuantityOrdered" - COALESCE("QuantityReceived", 0)) AS "Remaining",
                COALESCE(
                    NULLIF(poi."UnitPriceAtOrder", 0),
                    NULLIF(em."CommittedUnitCost", 0),
                    NULLIF(em."AwardedUnitCost", 0),
                    NULLIF(em."UnitCost", 0),
                    CASE COALESCE(m."CarryPriceSource", 'Internal')
                        WHEN 'Nedco' THEN NULLIF(m."NedcoPrice", 0)
                        WHEN 'Gescan' THEN NULLIF(m."GescanPrice", 0)
                        WHEN 'Eecol' THEN NULLIF(m."EecolPrice", 0)
                        WHEN 'Guillevin' THEN NULLIF(m."GuillevinPrice", 0)
                        ELSE NULLIF(m."InternalPrice", 0)
                    END,
                    0
                ) AS "UnitPriceAtOrder",
                COALESCE(
                    NULLIF(poi."LineTotal", 0),
                    COALESCE(poi."QuantityOrdered", 0) * COALESCE(
                        NULLIF(poi."UnitPriceAtOrder", 0),
                        NULLIF(em."CommittedUnitCost", 0),
                        NULLIF(em."AwardedUnitCost", 0),
                        NULLIF(em."UnitCost", 0),
                        CASE COALESCE(m."CarryPriceSource", 'Internal')
                            WHEN 'Nedco' THEN NULLIF(m."NedcoPrice", 0)
                            WHEN 'Gescan' THEN NULLIF(m."GescanPrice", 0)
                            WHEN 'Eecol' THEN NULLIF(m."EecolPrice", 0)
                            WHEN 'Guillevin' THEN NULLIF(m."GuillevinPrice", 0)
                            ELSE NULLIF(m."InternalPrice", 0)
                        END,
                        0
                    ),
                    0
                ) AS "LineTotal",
                poi."LastReceivedDate"
            FROM "PurchaseOrderItem" poi
            LEFT JOIN "EstimateMaterial" em ON poi."MaterialID" = em."EstimateMaterialID"
            LEFT JOIN "Material" m ON poi."CatalogItemID" = m."ItemID"
            WHERE poi."PurchaseOrderID" = %s
            ORDER BY poi."POItemID" ASC
        ''', (po_id,)) # <--- MY MISTAKE WAS HERE! I forgot to add this tuple!
        
        return cur.fetchall()
    finally:
        conn.close()

def search_po_items_by_part(search_term: str):
    """Searches all PO items for a specific part description."""
    ensure_purchase_schema()
    from neon_ai.database.connection import get_connection
    from psycopg2.extras import RealDictCursor
    conn = get_connection()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        search_pattern = f"%{search_term}%"
        cur.execute('''
            SELECT 
                poi."POItemID", po."PurchaseOrderID", s."SiteName",
                poi."Description", poi."QuantityOrdered", poi."QuantityReceived", 
                (poi."QuantityOrdered" - COALESCE(poi."QuantityReceived", 0)) AS "Remaining",
                poi."LastReceivedDate", po."Date" AS "PODate"
            FROM "PurchaseOrderItem" poi
            JOIN "PurchaseOrder" po ON poi."PurchaseOrderID" = po."PurchaseOrderID"
            LEFT JOIN "WorkOrder" wo ON po."WorkOrderID" = wo."WorkOrderID"
            LEFT JOIN "Site" s ON wo."SiteID" = s."SiteID"
            -- FIXED LOGIC: Removed the PartNumber check!
            WHERE poi."Description" ILIKE %s
            ORDER BY po."Date" DESC
        ''', (search_pattern,))
        return cur.fetchall()
    finally:
        conn.close()

def log_material_receipt_batch(packing_slip: str, receive_date: str, items_arriving: list):
    """
    Takes a list of items and saves them all in one massive transaction.
    items_arriving format: [(po_item_id, quantity_arrived_today), ...]
    """
    ensure_purchase_schema()
    from neon_ai.database.connection import get_connection
    conn = get_connection()
    cur = conn.cursor()
    try:
        po_ids = set()
        receipt_ids_by_po = {}
        # Loop through the shopping cart and update everything!
        for item_id, qty_arrived in items_arriving:
            cur.execute('SELECT "PurchaseOrderID" FROM "PurchaseOrderItem" WHERE "POItemID" = %s', (item_id,))
            row = cur.fetchone()
            if row and row.get("PurchaseOrderID"):
                po_id = row["PurchaseOrderID"]
                po_ids.add(po_id)
                if po_id not in receipt_ids_by_po:
                    receipt_ids_by_po[po_id] = _get_or_create_purchase_order_receipt(
                        cur,
                        po_id=po_id,
                        document_ref=packing_slip,
                        receive_date=receive_date,
                        document_type="Packing Slip",
                    )
            cur.execute('''
                UPDATE "PurchaseOrderItem"
                SET "QuantityReceived" = COALESCE("QuantityReceived", 0) + %s,
                    "LastReceivedDate" = %s,
                    "LastPackingSlip" = %s
                WHERE "POItemID" = %s
            ''', (qty_arrived, receive_date, packing_slip, item_id))

            if row and row.get("PurchaseOrderID"):
                receipt_id = receipt_ids_by_po[row["PurchaseOrderID"]]
                cur.execute(
                    '''
                    SELECT "ReceiptItemID", COALESCE("QuantityReceived", 0) AS "QuantityReceived"
                    FROM public."PurchaseOrderReceiptItem"
                    WHERE "ReceiptID" = %s AND "POItemID" = %s
                    LIMIT 1
                    ''',
                    (receipt_id, item_id),
                )
                receipt_item = cur.fetchone()
                if receipt_item and receipt_item.get("ReceiptItemID"):
                    cur.execute(
                        '''
                        UPDATE public."PurchaseOrderReceiptItem"
                        SET "QuantityReceived" = COALESCE("QuantityReceived", 0) + %s
                        WHERE "ReceiptItemID" = %s
                        ''',
                        (qty_arrived, receipt_item["ReceiptItemID"]),
                    )
                else:
                    cur.execute(
                        '''
                        INSERT INTO public."PurchaseOrderReceiptItem"
                        ("ReceiptID", "POItemID", "QuantityReceived")
                        VALUES (%s, %s, %s)
                        ''',
                        (receipt_id, item_id, qty_arrived),
                    )
        
        # Only commit if EVERY item succeeded
        conn.commit()
        for po_id in po_ids:
            update_purchase_order_receiving_status(po_id)
        return True
    except Exception as e:
        # If even one item fails, roll the whole thing back to protect the database!
        conn.rollback()
        raise e
    finally:
        conn.close()
